In [1]:
five_fold_files = {
    "week1": [
        "/kaggle/input/new-clean-mooccubex/clean_week1/train/5-folds/data_part_1.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week1/train/5-folds/data_part_2.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week1/train/5-folds/data_part_3.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week1/train/5-folds/data_part_4.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week1/train/5-folds/data_part_5.csv"
    ],
    "week2": [
        "/kaggle/input/new-clean-mooccubex/clean_week2/train/5-folds/data_part_1.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week2/train/5-folds/data_part_2.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week2/train/5-folds/data_part_3.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week2/train/5-folds/data_part_4.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week2/train/5-folds/data_part_5.csv"
    ],
    "week3": [
        "/kaggle/input/new-clean-mooccubex/clean_week3/train/5-folds/data_part_1.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week3/train/5-folds/data_part_2.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week3/train/5-folds/data_part_3.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week3/train/5-folds/data_part_4.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week3/train/5-folds/data_part_5.csv"
    ],
    "week4": [
        "/kaggle/input/new-clean-mooccubex/clean_week4/train/5-folds/data_part_1.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week4/train/5-folds/data_part_2.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week4/train/5-folds/data_part_3.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week4/train/5-folds/data_part_4.csv",
        "/kaggle/input/new-clean-mooccubex/clean_week4/train/5-folds/data_part_5.csv"
    ]
}

file_validation = {
    "week1": [
        "/kaggle/input/new-clean-mooccubex/clean_week1/val/val_week1.csv"
    ],
    "week2": [
        "/kaggle/input/new-clean-mooccubex/clean_week2/val/val_week1_2.csv"
    ],
    "week3": [
        "/kaggle/input/new-clean-mooccubex/clean_week3/val/val_week1_2_3.csv"
    ],
    "week4": [
        "/kaggle/input/new-clean-mooccubex/clean_week4/val/val_week1_2_3_4.csv"
    ]
}

file_test = {
    "week1": [
        "/kaggle/input/new-clean-mooccubex/clean_week1/test/test_week1.csv"
    ],
    "week2": [
        "/kaggle/input/new-clean-mooccubex/clean_week1/test/test_week2.csv"
    ],
    "week3": [
        "/kaggle/input/new-clean-mooccubex/clean_week1/test/test_week3.csv"
    ],
    "week4": [
        "/kaggle/input/new-clean-mooccubex/clean_week1/test/test_week4.csv"
    ]
}

In [2]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
import time
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_recall_fscore_support
from xgboost import XGBClassifier
import xgboost as xgb
import numpy as np

## Tìm siêu tham số tốt nhất cho từng tuần

In [3]:
# Tạo hàm train cho từng tuần
def train_week_model(week_number, file_paths_train, file_validataion):
       # Đọc dữ liệu
    train_data = pd.read_csv(file_paths_train)
    val_data = pd.read_csv(file_validataion)
    
    # Tách đặc trưng và nhãn
    X_train = train_data.drop(columns=["classification_encoded", "user_id", "course_id", "school", "enroll_time", "classification"])
    y_train = train_data["classification_encoded"]

    X_val = val_data.drop(columns=["classification_encoded", "user_id", "course_id", "school", "enroll_time", "classification"])
    y_val = val_data["classification_encoded"]
    
    # Áp dụng Over-sampling cho dữ liệu huấn luyện bằng SMOTE
    oversampler = SMOTE(sampling_strategy='auto', random_state=42)
    X_train_res, y_train_res = oversampler.fit_resample(X_train, y_train)
    
    model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')
       # # # Khởi tạo RandomSearch tuner
    # param_grid = {
    #     'n_estimators': [100, 200, 300],
    #     'max_depth': [3, 5, 7],
    #     'learning_rate': [0.05, 0.1, 0.2],
    #     'num_leaves': [20, 30, 40],
    #     'min_child_samples': [20, 30],
    #     'subsample': [0.8, 1.0],
    #     'colsample_bytree': [0.8, 1.0],
    #     'reg_alpha': [0, 0.1],
    #     'reg_lambda': [0, 0.1, 0.5]
    # }
    param_grid = {
        'n_estimators': [30, 50],  # Giảm số cây hơn nữa
        'max_depth': [1, 2],  # Độ sâu cây nhỏ hơn
        'learning_rate': [0.005, 0.01],  # Tốc độ học rất chậm
        'gamma': [1, 2],  # Regularization mạnh hơn
        'subsample': [0.5],  # Ngẫu nhiên hóa cao hơn
        'colsample_bytree': [0.5],  # Chọn ít đặc trưng hơn mỗi lần
        'min_child_weight': [10, 20],  # Tăng ngưỡng mẫu trong mỗi lá
        'reg_alpha': [1, 2],  # L1 regularization mạnh
        'reg_lambda': [2, 3],  # L2 regularization mạnh
        'max_delta_step': [5, 10]  # Giới hạn bước nhảy cao hơn
    }
    # Khởi tạo RandomSearch tuner
    grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=10, scoring='accuracy',
                              verbose=2, n_jobs=-1)
        
    
   # Huấn luyện mô hình với các siêu tham số tốt nhất
    grid_search.fit(X_train_res, y_train_res)

    # Đánh giá mô hình
    best_model = grid_search.best_estimator_
    y_pred = best_model.predict(X_val)
    # Trả về kết quả tối ưu cho tuần
    best_params = grid_search.best_params_
    return best_params

In [4]:
# Định nghĩa đường dẫn đến dữ liệu cho từng tuần
file_paths_train = {
    "week1": "/kaggle/input/new-clean-mooccubex/clean_week1/train/clean_data_week1.csv",
    "week2": "/kaggle/input/new-clean-mooccubex/clean_week2/train/clean_data_week2.csv",
    "week3": "/kaggle/input/new-clean-mooccubex/clean_week3/train/clean_data_week3.csv",
    "week4": "/kaggle/input/new-clean-mooccubex/clean_week4/train/clean_data_week4.csv"
}

file_validation = {
    "week1": "/kaggle/input/new-clean-mooccubex/clean_week1/val/val_week1.csv",
    "week2": "/kaggle/input/new-clean-mooccubex/clean_week2/val/val_week1_2.csv",
    "week3": "/kaggle/input/new-clean-mooccubex/clean_week3/val/val_week1_2_3.csv",
    "week4": "/kaggle/input/new-clean-mooccubex/clean_week4/val/val_week1_2_3_4.csv"
}

In [5]:
# Tìm tham số tốt nhất cho từng tuần
best_params_week1 = train_week_model(1, file_paths_train["week1"], file_validation["week1"])
best_params_week2 = train_week_model(2, file_paths_train["week2"], file_validation["week2"])
best_params_week3 = train_week_model(3, file_paths_train["week3"], file_validation["week3"])
best_params_week4 = train_week_model(4, file_paths_train["week4"], file_validation["week4"])

# In thông tin chi tiết các tham số tối ưu
print("Best Parameters for Week 1:")
for param_name, param_value in best_params_week1.items():
       print(f"{param_name}: {param_value}")

print("\nBest Parameters for Week 2:")
for param_name, param_value in best_params_week2.items():
       print(f"{param_name}: {param_value}")

print("\nBest Parameters for Week 3:")
for param_name, param_value in best_params_week3.items():
       print(f"{param_name}: {param_value}")

print("\nBest Parameters for Week 4:")
for param_name, param_value in best_params_week4.items():
       print(f"{param_name}: {param_value}")

Fitting 10 folds for each of 256 candidates, totalling 2560 fits
Fitting 10 folds for each of 256 candidates, totalling 2560 fits
Fitting 10 folds for each of 256 candidates, totalling 2560 fits
Fitting 10 folds for each of 256 candidates, totalling 2560 fits


/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


Best Parameters for Week 1:
colsample_bytree: 0.5
gamma: 1
learning_rate: 0.01
max_delta_step: 5
max_depth: 2
min_child_weight: 10
n_estimators: 30
reg_alpha: 1
reg_lambda: 3
subsample: 0.5

Best Parameters for Week 2:
colsample_bytree: 0.5
gamma: 1
learning_rate: 0.01
max_delta_step: 5
max_depth: 2
min_child_weight: 10
n_estimators: 50
reg_alpha: 2
reg_lambda: 2
subsample: 0.5

Best Parameters for Week 3:
colsample_bytree: 0.5
gamma: 1
learning_rate: 0.005
max_delta_step: 5
max_depth: 2
min_child_weight: 20
n_estimators: 30
reg_alpha: 1
reg_lambda: 3
subsample: 0.5

Best Parameters for Week 4:
colsample_bytree: 0.5
gamma: 1
learning_rate: 0.005
max_delta_step: 5
max_depth: 2
min_child_weight: 10
n_estimators: 30
reg_alpha: 1
reg_lambda: 2
subsample: 0.5


In [6]:
# Danh sách tham số tốt nhất
best_params = {
    "week1": best_params_week1,
    "week2": best_params_week2,
    "week3": best_params_week3,
    "week4": best_params_week4
}

## XGBoost với các tham sốt nhất cho mỗi tuần

In [7]:
# Biến lưu kết quả tổng quát
overall_results_5folds = []

# Lặp qua từng tuần
for week, file_paths in five_fold_files.items():
    print(f"\nProcessing {week} with best parameters...")
    params = best_params[week]
    print(f"best parameters for {week}: {params}")
    
    # Biến lưu kết quả cho từng tuần
    week_results = {
        "week": week,
        "accuracy_per_fold": [],
        "precision_per_label": [],
        "recall_per_label": [],
        "f1_score_per_label": [],
        "confusion_matrices": [],
        "train_times": [],
        "test_times": []
    }

    # Lặp qua từng fold
    for i in range(len(file_paths)):
        print(f"Fold {i+1}: Using file {file_paths[i]} as test set")
        
        # Tải dữ liệu
        test_data = pd.read_csv(file_paths[i])
        train_data = pd.concat([pd.read_csv(file_paths[j]) for j in range(len(file_paths)) if j != i])
        
        # Tách X và y
        X_train = train_data.drop(columns=["classification_encoded", "user_id",
                                           "course_id", "school", "enroll_time", "classification"])
        y_train = train_data['classification_encoded']
        
        X_test = test_data.drop(columns=["classification_encoded", "user_id",
                                         "course_id", "school", "enroll_time", "classification"])
        y_test = test_data['classification_encoded']


        # Xây dựng mô hình với tham số tốt nhất
        model = xgb.XGBClassifier(**params)
        
        # Bắt đầu tính thời gian huấn luyện
        start_train = time.time()
        model.fit(X_train, y_train)
        end_train = time.time()
        
        # Bắt đầu tính thời gian kiểm thử
        start_test = time.time()
        y_pred = model.predict(X_test)
        end_test = time.time()
        
        # Tính thời gian và lưu lại
        train_time = end_train - start_train
        test_time = end_test - start_test
        week_results["train_times"].append(train_time)
        week_results["test_times"].append(test_time)

        # Đánh giá mô hình trên tập kiểm thử của fold hiện tại
        accuracy = accuracy_score(y_test, y_pred)
        week_results["accuracy_per_fold"].append(accuracy)
        # Dự đoán

        
        # Tính các chỉ số cho mỗi fold
        precision, recall, f1, _ = precision_recall_fscore_support(y_test, y_pred, average=None)
        conf_matrix = confusion_matrix(y_test, y_pred)
        
        week_results["precision_per_label"].append(precision)
        week_results["recall_per_label"].append(recall)
        week_results["f1_score_per_label"].append(f1)
        week_results["confusion_matrices"].append(conf_matrix)

    # Tính trung bình cho từng nhãn
    average_precision_per_label = np.mean(week_results["precision_per_label"], axis=0)
    average_recall_per_label = np.mean(week_results["recall_per_label"], axis=0)
    average_f1_per_label = np.mean(week_results["f1_score_per_label"], axis=0)
    average_confusion_matrix = np.mean(week_results["confusion_matrices"], axis=0)
    average_train_time = sum(week_results["train_times"]) / len(week_results["train_times"])
    average_test_time = sum(week_results["test_times"]) / len(week_results["test_times"])
    
    # Tạo DataFrame cho precision, recall, f1-score
    labels = np.unique(y_test)  # Lấy nhãn từ y_test_classes
    metrics_df = pd.DataFrame({
        "Label": labels,
        "Average Precision": average_precision_per_label,
        "Average Recall": average_recall_per_label,
        "Average F1-Score": average_f1_per_label
    })
    
    # Tạo DataFrame cho confusion matrix|
    confusion_df = pd.DataFrame(average_confusion_matrix, index=labels, columns=labels)
    
    # In kết quả
    print("\n=== Average Precision, Recall, F1-Score per Label ===")
    print(metrics_df)
    print("\n=== Average Confusion Matrix ===")
    print(confusion_df)

    # Lưu kết quả tuần vào kết quả tổng quát
    week_results["average_train_times"] = average_train_time
    week_results["average_test_times"] = average_test_time
    week_results["average_metrics_df"] = metrics_df
    week_results["average_confusion_matrix"] = confusion_df
    overall_results_5folds.append(week_results)


Processing week1 with best parameters...
best parameters for week1: {'colsample_bytree': 0.5, 'gamma': 1, 'learning_rate': 0.01, 'max_delta_step': 5, 'max_depth': 2, 'min_child_weight': 10, 'n_estimators': 30, 'reg_alpha': 1, 'reg_lambda': 3, 'subsample': 0.5}
Fold 1: Using file /kaggle/input/new-clean-mooccubex/clean_week1/train/5-folds/data_part_1.csv as test set
Fold 2: Using file /kaggle/input/new-clean-mooccubex/clean_week1/train/5-folds/data_part_2.csv as test set
Fold 3: Using file /kaggle/input/new-clean-mooccubex/clean_week1/train/5-folds/data_part_3.csv as test set
Fold 4: Using file /kaggle/input/new-clean-mooccubex/clean_week1/train/5-folds/data_part_4.csv as test set
Fold 5: Using file /kaggle/input/new-clean-mooccubex/clean_week1/train/5-folds/data_part_5.csv as test set

=== Average Precision, Recall, F1-Score per Label ===
   Label  Average Precision  Average Recall  Average F1-Score
0      0           0.997339        0.999333          0.998335
1      1           0.990

## Kết quả 5-folds

In [8]:
# Duyệt qua các tuần trong overall_results
for week_result in overall_results_5folds:
    week = week_result["week"]
    average_train_time = np.mean(week_result["train_times"])
    average_test_time = np.mean(week_result["test_times"])
    average_metrics_df = week_result["average_metrics_df"]
    average_confusion_matrix = week_result["average_confusion_matrix"]
    
    # In kết quả
    print(f"\n=== Results for {week} ===")
    print(f"Average Train Time: {average_train_time:.4f} seconds")
    print(f"Average Test Time: {average_test_time:.4f} seconds")
    print("\nAverage Precision, Recall, F1-Score per Label:")
    print(average_metrics_df)
    print("\nAverage Confusion Matrix:")
    print(average_confusion_matrix)



=== Results for week1 ===
Average Train Time: 0.0937 seconds
Average Test Time: 0.0050 seconds

Average Precision, Recall, F1-Score per Label:
   Label  Average Precision  Average Recall  Average F1-Score
0      0           0.997339        0.999333          0.998335
1      1           0.990803        0.974896          0.982698
2      2           1.000000        0.996356          0.998169
3      3           1.000000        0.980838          0.990277
4      4           0.996767        0.999251          0.998007

Average Confusion Matrix:
       0     1      2      3       4
0  599.6   0.0    0.0    0.0     0.4
1    0.6  85.4    0.0    0.0     1.6
2    0.2   0.0  163.8    0.0     0.4
3    0.4   0.0    0.0  163.8     2.8
4    0.4   0.8    0.0    0.0  1602.2

=== Results for week2 ===
Average Train Time: 0.1623 seconds
Average Test Time: 0.0064 seconds

Average Precision, Recall, F1-Score per Label:
   Label  Average Precision  Average Recall  Average F1-Score
0      0           0.999667  

## Test trên tập test

In [9]:
# Mảng lưu dữ liệu của các tuần
results = []

def process_week(week_num, best_params, results):
    print(f"\n=== Processing Week {week_num} ===")
    params = best_params[week]
    # Đường dẫn tới dữ liệu tuần tương ứng
    train_path = f"/kaggle/input/new-clean-mooccubex/clean_week{week_num}/train/clean_data_week{week_num}.csv"
    test_path = f"/kaggle/input/new-clean-mooccubex/clean_week{week_num}/test/test_week{week_num}.csv"
    
    # Load dữ liệu
    train_data = pd.read_csv(train_path)
    test_data = pd.read_csv(test_path)
    
    # Tách X và y
    X_train = train_data.drop(columns=["classification_encoded", "user_id",
                                       "course_id", "school", "enroll_time", "classification"])
    y_train = train_data['classification_encoded']
    
    X_test = test_data.drop(columns=["classification_encoded", "user_id",
                                     "course_id", "school", "enroll_time", "classification"])
    y_test = test_data['classification_encoded']

    # Áp dụng SMOTE cho tập huấn luyện
    smote = SMOTE(random_state=42)
    X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

    # Xây dựng mô hình với tham số tốt nhất
    model = xgb.XGBClassifier(**params)
    
    # Huấn luyện mô hình
    start_train = time.time()
    model.fit(X_train, y_train)
    end_train = time.time()
    
    # Kiểm thử mô hình
    start_test = time.time()
    y_pred = model.predict(X_test)
    end_test = time.time()
    
    # Tính thời gian huấn luyện và kiểm thử
    train_time = end_train - start_train
    test_time = end_test - start_test
    
    
    precision, recall, f1, _ = precision_recall_fscore_support(y_test, y_pred, average=None)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Lưu kết quả vào mảng
    results.append({
        "week": week_num,
        "train_time": train_time,
        "test_time": test_time,
        "precision": precision,
        "recall": recall,
        "f1_score": f1,
        "confusion_matrix": conf_matrix
    })
    
    print("\n=== Precision, Recall, F1-Score per Label ===")
    print(pd.DataFrame({
        "Label": np.unique(y_test),
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1
    }))
    print("\n=== Confusion Matrix ===")
    print(pd.DataFrame(conf_matrix, index=np.unique(y_test), columns=np.unique(y_test)))
    
    print(f"\nTrain Time: {train_time:.2f} seconds")
    print(f"Test Time: {test_time:.2f} seconds")

In [10]:
process_week(1, best_params, results)


=== Processing Week 1 ===

=== Precision, Recall, F1-Score per Label ===
   Label  Precision    Recall  F1-Score
0      0   0.994695  1.000000  0.997340
1      1   1.000000  1.000000  1.000000
2      2   1.000000  1.000000  1.000000
3      3   1.000000  0.971429  0.985507
4      4   0.998008  0.999003  0.998505

=== Confusion Matrix ===
     0   1    2    3     4
0  375   0    0    0     0
1    0  54    0    0     0
2    0   0  103    0     0
3    1   0    0  102     2
4    1   0    0    0  1002

Train Time: 0.11 seconds
Test Time: 0.00 seconds


In [11]:
process_week(2, best_params, results)


=== Processing Week 2 ===

=== Precision, Recall, F1-Score per Label ===
   Label  Precision    Recall  F1-Score
0      0    0.99734  1.000000  0.998668
1      1    1.00000  0.981481  0.990654
2      2    1.00000  1.000000  1.000000
3      3    1.00000  1.000000  1.000000
4      4    1.00000  1.000000  1.000000

=== Confusion Matrix ===
     0   1    2    3     4
0  375   0    0    0     0
1    1  53    0    0     0
2    0   0  103    0     0
3    0   0    0  105     0
4    0   0    0    0  1003

Train Time: 0.12 seconds
Test Time: 0.01 seconds


In [12]:
process_week(3, best_params, results)


=== Processing Week 3 ===

=== Precision, Recall, F1-Score per Label ===
   Label  Precision  Recall  F1-Score
0      0        1.0     1.0       1.0
1      1        1.0     1.0       1.0
2      2        1.0     1.0       1.0
3      3        1.0     1.0       1.0
4      4        1.0     1.0       1.0

=== Confusion Matrix ===
     0   1    2    3     4
0  375   0    0    0     0
1    0  54    0    0     0
2    0   0  103    0     0
3    0   0    0  105     0
4    0   0    0    0  1003

Train Time: 0.14 seconds
Test Time: 0.01 seconds


In [13]:
process_week(4, best_params, results)


=== Processing Week 4 ===

=== Precision, Recall, F1-Score per Label ===
   Label  Precision  Recall  F1-Score
0      0        1.0     1.0       1.0
1      1        1.0     1.0       1.0
2      2        1.0     1.0       1.0
3      3        1.0     1.0       1.0
4      4        1.0     1.0       1.0

=== Confusion Matrix ===
     0   1    2    3     4
0  375   0    0    0     0
1    0  54    0    0     0
2    0   0  103    0     0
3    0   0    0  105     0
4    0   0    0    0  1003

Train Time: 0.15 seconds
Test Time: 0.01 seconds


In [14]:
# Hiển thị dữ liệu của các tuần
print("\n=== Summary Results for All Weeks ===")
for result in results:
    print(f"Week {result['week']}:")
    print(f"  Train Time: {result['train_time']:.2f} seconds")
    print(f"  Test Time: {result['test_time']:.2f} seconds")
    print(f"  Precision: {result['precision']}")
    print(f"  Recall: {result['recall']}")
    print(f"  F1-Score: {result['f1_score']}")
    print(f"  Confusion Matrix:\n{result['confusion_matrix']}")


=== Summary Results for All Weeks ===
Week 1:
  Train Time: 0.11 seconds
  Test Time: 0.00 seconds
  Precision: [0.99469496 1.         1.         1.         0.99800797]
  Recall: [1.         1.         1.         0.97142857 0.99900299]
  F1-Score: [0.99734043 1.         1.         0.98550725 0.99850523]
  Confusion Matrix:
[[ 375    0    0    0    0]
 [   0   54    0    0    0]
 [   0    0  103    0    0]
 [   1    0    0  102    2]
 [   1    0    0    0 1002]]
Week 2:
  Train Time: 0.12 seconds
  Test Time: 0.01 seconds
  Precision: [0.99734043 1.         1.         1.         1.        ]
  Recall: [1.         0.98148148 1.         1.         1.        ]
  F1-Score: [0.99866844 0.99065421 1.         1.         1.        ]
  Confusion Matrix:
[[ 375    0    0    0    0]
 [   1   53    0    0    0]
 [   0    0  103    0    0]
 [   0    0    0  105    0]
 [   0    0    0    0 1003]]
Week 3:
  Train Time: 0.14 seconds
  Test Time: 0.01 seconds
  Precision: [1. 1. 1. 1. 1.]
  Recall: [1. 